BASEURL: 'https://developers.zomato.com/api/v2.1'
CitiesResource: '/cities'
BengaluruCityQuery: '?q=bengaluru'
CategoriesResource: '/categories'
CollectionsResource: '/collections'
CuisinesResource: '/cuisines'
LocationsResource: '/locations'
RestaurantResource: '/restaurant'
ReviewsResource: '/reviews'
SearchResource: '/search'
DailyMenuResource: '/dailymenu'
LocationDetailsResource: '/location_details'
EstablishmentsResource: '/establishments'
GeocodeResource: '/geocode'
BengaluruCityIdQuery: '?city_id=4'
BengaluruEntityIdQuery: '?entity_id=4'
BengaluruEntityTypeQuery: 'entity_type=city'
ResIdQuery: '?res_id=16505937'
